/**
 * Created by Ar Razy Fathan Rabbani on 09/05/23.
 */

object Version {
    const val kotlinVersion = "1.8.0"
    const val coreKtx = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.4"
    const val jUnit = "4.13.2"
    const val androidJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val retrofit = "2.9.0"
    const val loggingInterceptor = "5.0.0-alpha.10"
    const val glide = "4.13.2"
    const val navigationComponent = "2.5.3"
    const val room = "2.5.1"
    const val hilt = "2.44"
    const val activityKtx = "1.7.0"
    const val fragmentKtx = "1.5.6"
    const val lifecycleExt = "2.2.0"
    const val viewModelKtx = "2.6.1"
    const val liveDataKtx = "2.6.1"
    const val lifecycleComponent = "2.6.1"
    const val coroutines = "1.6.4"
    const val lottie = "5.0.3"
    const val timeAgo = "4.0.3"
    const val swipeRefreshLayout = "1.1.0"
    const val firebaseBom = "30.1.0"
    const val stickyScrollView = "1.0.3"
    const val coil = "2.3.0"
    const val androidBrowser = "1.5.0"
    const val navigationSafeArgs = "2.5.3"
    const val timber = "5.0.1"
    const val composeBom = "2023.05.01"
    const val accompanistThemeAdapter = "0.30.1"
    const val coilCompose = "2.4.0"
    const val constraintLayoutCompose = "1.0.1"
    const val swipeActionCompose = "1.1.1"
}
